### ISSUE TITLE
Example data - pysam.utils.SamtoolsError

### ISSUE THREAD

**Issue by GuillaumeMEXP** [ryanabo/BreaKmer#3]
Hello ! 

Trying to run the example data, with the aim to compare eventually the .bam file provided with mine, I got this error : 
the connexion to the blat server and the preparation of the reference data went very well
pysam is installed (with pip command) : pysam in ./.local/lib/python2.7/site-packages/pysam-0.13-py2.7-linux-x86_64.egg

```
guillaume@guillaume-linux[guillaume] python /home/guillaume/Downloads/BreaKmer-master/breakmer.py run -n 2 -c /home/guillaume/Downloads/BreaKmer-master/example_data/breakmer_test_master.cfg
Traceback (most recent call last):
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer.py", line 74, in <module>
    RUNNER.run()
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer/processor/analysis.py", line 143, in run
    if not trgt.get_sv_reads():
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer/processor/target.py", line 221, in get_sv_reads
    self.extract_bam_reads('sv')
  File "/home/guillaume/Downloads/BreaKmer-master/breakmer/processor/target.py", line 394, in extract_bam_reads
    pysam.sort(self.files['sv_bam'], self.files['sv_bam_sorted'].replace('.bam', ''))
  File "/home/guillaume/.local/lib/python2.7/site-packages/pysam-0.13-py2.7-linux-x86_64.egg/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\nUsage: samtools sort [options...] [in.bam]\nOptions:\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n  -n         Sort by read name\n  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)\n  -o FILE    Write final output to FILE rather than standard output\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n      --input-fmt-option OPT[=VAL]\n               Specify a single input file format option in the form\n               of OPTION or OPTION=VALUE\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n               Specify output format (SAM, BAM, CRAM)\n      --output-fmt-option OPT[=VAL]\n               Specify a single output file format option in the form\n               of OPTION or OPTION=VALUE\n      --reference FILE\n               Reference sequence FASTA FILE [null]\n  -@, --threads INT\n               Number of additional threads to use [0]\n'
```

Does it give you an idea ? Do I do something wrong ? 
Thanks a lot !!
Best, 
Will

**Comment by ydy1127** [comment]
> Hello !
> 
> Trying to run the example data, with the aim to compare eventually the .bam file provided with mine, I got this error :
> the connexion to the blat server and the preparation of the reference data went very well
> pysam is installed (with pip command) : pysam in ./.local/lib/python2.7/site-packages/pysam-0.13-py2.7-linux-x86_64.egg
> 
> ```
> guillaume@guillaume-linux[guillaume] python /home/guillaume/Downloads/BreaKmer-master/breakmer.py run -n 2 -c /home/guillaume/Downloads/BreaKmer-master/example_data/breakmer_test_master.cfg
> Traceback (most recent call last):
>   File "/home/guillaume/Downloads/BreaKmer-master/breakmer.py", line 74, in <module>
>     RUNNER.run()
>   File "/home/guillaume/Downloads/BreaKmer-master/breakmer/processor/analysis.py", line 143, in run
>     if not trgt.get_sv_reads():
>   File "/home/guillaume/Downloads/BreaKmer-master/breakmer/processor/target.py", line 221, in get_sv_reads
>     self.extract_bam_reads('sv')
>   File "/home/guillaume/Downloads/BreaKmer-master/breakmer/processor/target.py", line 394, in extract_bam_reads
>     pysam.sort(self.files['sv_bam'], self.files['sv_bam_sorted'].replace('.bam', ''))
>   File "/home/guillaume/.local/lib/python2.7/site-packages/pysam-0.13-py2.7-linux-x86_64.egg/pysam/utils.py", line 75, in __call__
>     stderr))
> pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\nUsage: samtools sort [options...] [in.bam]\nOptions:\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n  -n         Sort by read name\n  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)\n  -o FILE    Write final output to FILE rather than standard output\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n      --input-fmt-option OPT[=VAL]\n               Specify a single input file format option in the form\n               of OPTION or OPTION=VALUE\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n               Specify output format (SAM, BAM, CRAM)\n      --output-fmt-option OPT[=VAL]\n               Specify a single output file format option in the form\n               of OPTION or OPTION=VALUE\n      --reference FILE\n               Reference sequence FASTA FILE [null]\n  -@, --threads INT\n               Number of additional threads to use [0]\n'
> ```
> 
> Does it give you an idea ? Do I do something wrong ?
> Thanks a lot !!
> Best,
> Will
 
 Hi!
 
 As a user of this software, I have encountered the same problem as you. May I ask whether your 
 problem has been solved and whether the test data can be completed?

Looking forward to your reply!
